ALTER TABLE modules
    ADD COLUMN chemin_source VARCHAR(500) DEFAULT NULL,
    ADD COLUMN point_entree VARCHAR(100) DEFAULT 'index.php',
    ADD COLUMN cles_env JSON DEFAULT NULL,
    ADD COLUMN routes_config JSON DEFAULT NULL,
    ADD COLUMN passthrough_all TINYINT(1) NOT NULL DEFAULT 0,
    ADD COLUMN installe_par INT UNSIGNED DEFAULT NULL,
    ADD COLUMN installe_le DATETIME DEFAULT NULL;
